twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/Img': images
        '%kernel.project_dir%/public/build': css
    globals:
        posterPath: '%app.path.poster_file%/'
        actorImgPath: '%app.path.actorImg_file%/'
