# route prioritaires sur les configuration locales pour la langue .
index:
    path: /
    controller: App\Controller\DefaultController::index

# config/routes.yaml
# load some routes - one should ultimately have the path "/app"

